= Asciidoctor Reducer Changelog
:url-repo: https://github.com/asciidoctor/asciidoctor-reducer

This document provides a high-level view of the changes to the Asciidoctor Reducer by release.
For a detailed view of what has changed, refer to the {url-repo}/commits/main[commit history] on GitHub.

== Unreleased

=== Changed

* Rename PreprocessorReader ext module to PreprocessorReaderTracker
* Encapsulate logic to enhance PreprocessorReader inside PreprocessorReaderTracker module
* Only reload document if source lines have changed; otherwise, update source lines on reader directly
* Change default safe mode for CLI to :unsafe

== 1.0.0.alpha.2 (2022-01-27) - @mojavelinux

=== Added

* Add `-a` / `--attribute` option to CLI for setting an AsciiDoc document attribute at runtime (#6)

=== Changed

* Reduce preprocessor conditionals by default; add option (`--preserve-conditionals` / `:preserve_conditionals`) to preserve them (#8)
* Don't enable sourcemap automatically (#4)
* Don't override logger by default; instead, rely on `:logger` API option to change logger
* Add `--log-level` option to CLI to set severity level on logger (#9)
* Add `-q` / `--quiet` option to CLI to suppress log messages (#9)
* Reserve zero index in include replacements for top-level document

=== Fixed

* Preserve return value when overridding `preprocess_include_directive` method

== 1.0.0.alpha.1 (2022-01-12) - @mojavelinux

Initial release.

=== Details

{url-repo}/releases/tag/v1.0.0.alpha.1[git tag]

=== Details

{url-repo}/releases/tag/v1.0.0.alpha.2[git tag]
