= Asciidoctor Reducer
Dan Allen <https://github.com/mojavelinux[@mojavelinux]>
// settings:
:idprefix:
:idseparator: -
ifndef::env-github[:icons: font]
ifdef::env-github[]
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

Asciidoctor Reducer is a tool that reduces an AsciiDoc document with includes to a single document by expanding the includes reachable from the specified parent document.
If the document does not contain any includes, the tool returns the original source.

IMPORTANT: This project is still in prototype.
As such, there is no release available.

== Usage

=== As extension

You can use this tool as an Asciidoctor extension when using the Asciidoctor API.
To do so, require it before calling the `Asciidoctor.load` method.

[,ruby]
----
require 'asciidoctor/reducer'
----

Next, load a parent document that contains includes.

[,ruby]
----
doc = Asciidoctor.load_file 'sample.adoc', safe: :safe
----

Finally, you can retrieve the reduced source from the returned document.

[,ruby]
----
puts doc.source
----

You can write this source to a file to save the reduced document.

== Copyright and License

Copyright (C) 2021-present Dan Allen.
Use of this software is granted under the terms of the MIT License.

See the link:LICENSE[LICENSE] for the full license text.

== Trademarks

AsciiDoc(R) and AsciiDoc Language(TM) are trademarks of the Eclipse Foundation, Inc.
